name: Build-Application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone the project repository
        run: |
          sudo chmod -R 777 /mnt
          git clone "https://github.com/MayankgudadheCI/project.git" /mnt/project

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y

      - name: Build with Maven
        run: |
          cd /mnt/project
          mvn clean install
          mvn package

      - name: Install docker
        run: |
          sudo apt-get install docker -y

      - name: Cloning Secret repo
        env:
          MY_TOKEN: ${{secrets.MY_TOKEN}}
        run: |
          sudo chmod -R 777 /mnt
          sudo mkdir /mnt/mayank
          sudo chmod -R 777 /mnt/mayank
          sudo mkdir /mnt/test
          git clone "https://x-access-token:${MY_TOKEN}@github.com/MayankgudadheCI/private_repo.git" /mnt/mayank

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: LoginWebApp
          path: /mnt/project/target/LoginWebApp.war
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download war file
        uses: actions/download-artifact@v3
        with:
          name: LoginWebApp

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  
       
      - name: Check if S3 bucket exists
        run: |
          if aws s3api head-bucket --bucket deploy-mayank-mumbai 2>/dev/null; then
            echo "Bucket already exists."
          else
            echo "Creating bucket..."
          aws s3api create-bucket --bucket deploy-mayank-mumbai --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1
          fi

      - name: Upload artifacts to S3
        run: |
          aws s3 cp LoginWebApp.war s3://deploy-mayank-mumbai/LoginWebApp.war

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Get terraform script
        run: |
           sudo mkdir /mnt/infra
           sudo chmod -R 777 /mnt/infra
           git clone "https://github.com/MayankgudadheCI/Test.git" /mnt/infra
     
      - name: Terraform Plan
        run: |
          cd /mnt/infra
          terraform plan
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}




               



