name: Build-Application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone the project repository
        run: |
          sudo chmod -R 777 /mnt
          git clone "https://github.com/MayankgudadheCI/project.git" /mnt/project

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y

      - name: Build with Maven
        run: |
          cd /mnt/project
          mvn clean install
          mvn package

      - name: Install docker
        run: |
          sudo apt-get install docker -y

      - name: Cloning Secret repo
        env:
          MY_TOKEN: ${{secrets.MY_TOKEN}}
        run: |
          sudo chmod -R 777 /mnt
          sudo mkdir /mnt/mayank
          sudo chmod -R 777 /mnt/mayank
          sudo mkdir /mnt/test
          git clone "https://x-access-token:${MY_TOKEN}@github.com/MayankgudadheCI/private_repo.git" /mnt/mayank

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: LoginWebApp
          path: /mnt/project/target/LoginWebApp.war
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download war file
        uses: actions/download-artifact@v3
        with:
          name: LoginWebApp

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          curl -O https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/LoginWebApp.war
          sudo scp -i private_key.pem LoginWebApp ec2@ec2-3-109-202-72.ap-south-1.compute.amazonaws.com:/root/server/apache-tomcat-9.0.94/webapps


