name: Build-Application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run:  |
          cd /mnt
          git clone "https://github.com/MayankgudadheCI/project.git"
      - name: Run a multi-line script
        run: |
          apt-get update
          apt-get install maven -y
          cd /mnt
          mvn clean install
