name: Destroy Infrastructure

on:
  workflow_dispatch:  # Allows manual triggering of this workflow from the GitHub UI
    inputs:
      environment:
        description: 'The environment to destroy'
        required: true
        default: 'production'

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform Configuration
        uses: actions/checkout@v4
        with:
          repository: 'your-repo/terraform-config'  # Replace with your repo containing Terraform configs
          path: /mnt/infra

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Adjust to your region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: |
          cd /mnt/infra
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan Destroy
        run: |
          cd /mnt/infra
          terraform plan -destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        run: |
          cd /mnt/infra
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

