name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Get terraform script
      run: |
        sudo apt-get update
        sudo apt-get install git -y
        sudo mkdir -p /mnt/infra
        sudo chmod -R 777 /mnt/infra
        sudo chown -R $(sudo whoami):$(sudo whoami) /mnt/infra
        git clone "https://github.com/MayankgudadheCI/Test1.git" /mnt/infra

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: List Terraform Directory
      run: ls -al /mnt/infra/Terraform

    - name: Initialize Terraform
      run: |
        cd /mnt/infra/Terraform
        terraform init -backend=true -backend-config=bucket=deploy-mayank-mumbai -backend-config=key=terraform/state/terraform.tfstate -backend-config=region=ap-south-1 -no-color

    - name: Terraform Destroy
      run: |
        cd /mnt/infra/Terraform
        terraform destroy -auto-approve -no-color

    - name: Clean up terraform.tfstate
      run: |
        cd /mnt/infra/Terraform
        rm -f terraform.tfstate || true
