name: Destroy Infrastructure

on:
  workflow_dispatch: # Allows you to manually trigger this workflow from the GitHub Actions tab

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/setup-aws-cli@v2
      with:
        aws-region: ap-south-1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 

    - name: Download terraform.tfstate from S3
      run: |
        aws s3 cp s3://deploy-mayank-mumbai/terraform/state/terraform.tfstate

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_region: ap-south-1

    - name: Clean up terraform.tfstate
      run: rm -f terraform.tfstate

