name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    
    - name: Set up AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Get terraform script
        run: |
           git clone "https://github.com/MayankgudadheCI/Test.git" 
           
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Download terraform.tfstate from S3
      run: aws s3 cp s3://deploy-mayank-mumbai/terraform/state/terraform.tfstate terraform.tfstate

    - name: Clean Terraform Cache
      run: rm -rf .terraform

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve

    - name: Clean up terraform.tfstate
      run: rm -f terraform.tfstate
