name: Building Docker image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install docker
        run: |
          sudo apt-get install docker -y

      - name: Cloning dockerfile
        run: |
          sudo chmod -R 777 /mnt
          sudo mkdir /mnt/docker
          sudo chmod -R 777 /mnt/docker
          git clone "https://github.com/MayankgudadheCI/Mayank_IMP.git" /mnt/docker

      - name: Build image
        run: |
           sudo docker build -t myimg:1.0 /mnt/docker


