name: Run Inspec Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  inspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Inspec Version
        run: |
          inspec version

      - name: Run Inspec tests
        run: |
          inspec exec ./inspec/profile/inspec.rb
