name: InSpec Tests

on:
 workflow_dispatch:

jobs:
  inspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you need

      - name: Install InSpec
        run: |
          gem install inspec
          echo "$(ruby -e 'puts Gem.bindir')" >> $GITHUB_ENV  # Add InSpec bin to PATH
          inspec version  # Optional: to verify the installation

      - name: Run InSpec Tests
        env:
          VPC_ID: ${{ secrets.VPC_ID }}
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
        run: inspec exec inspec/profile/inspec.rb
