name: InSpec Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  inspec_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  
          
      - name: Install InSpec
        run: gem install inspec

      - name: Run InSpec Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: inspec exec ./my_profile -t aws://
