name: InSpec Tests

on:
  workflow_dispatch:

jobs:
  inspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you need
          
      - name: Install InSpec
        run: |
          gem install inspec
          inspec version  # Optional: to verify the installation

      - name: Run InSpec Tests
        env:
          VPC_ID: ${{ secrets.VPC_ID }}
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
        run: inspec exec controls/aws_security_group_tests.rb
