name: Run Inspec Tests

on:
  push:
    branches:
      - main  # Change as needed
  pull_request:

jobs:
  inspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Inspec tests
        run: |
          inspec exec ./inspec/profile/inspec.rb  # Adjust the path as needed
