name: InSpec Tests

on:
  workflow_dispatch:
jobs:
  inspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Download Terraform State
        run: |
          aws s3 cp s3://deploy-mayank-mumbai/terraform/state/terraform.tfstate ./terraform.tfstate

      - name: Get VPC ID and Instance ID from tfstate
        id: tfstate
        run: |
          set -e
          VPC_ID=$(jq -r '.resources[] | select(.type=="aws_vpc") | .instances[0].attributes.id' terraform.tfstate)
          INSTANCE_ID=$(jq -r '.resources[] | select(.type=="aws_instance") | .instances[0].attributes.id' terraform.tfstate)
          echo "vpc_id=$VPC_ID" >> $GITHUB_ENV
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Bundler Locally
        run: |
          gem install bundler --user-install
          echo "export PATH=\$PATH:\$HOME/.gem/ruby/3.0.0/bin" >> $GITHUB_ENV

      - name: Install InSpec via Bundler
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'inspec'" >> Gemfile
          ~/.gem/ruby/3.0.0/bin/bundle install --path vendor/bundle

      - name: Run InSpec Tests
        run: |
          ~/.gem/ruby/3.0.0/bin/inspec exec ./inspec/profile -t aws://
