name: InSpec Testing

on:
  workflow_dispatch:

jobs:
  inspec_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you need

      - name: Install InSpec
        run: |
          gem install inspec
          echo "InSpec installed, version:"
          inspec --version || echo "InSpec command not found"  # Check if InSpec installed correctly

      - name: Run InSpec Tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Running InSpec tests..."
          inspec exec ./my_profile -t aws:// || echo "Failed to run InSpec tests"
